#!/usr/bin/env bash

################################################################################
# Checks to make sure that all the code is covered. Fails if coverage is not
# 100% and lists the lines that are not covered
#
# Usage:
#     check/coverage
################################################################################

# Get the working directory to the repo root.
cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$(git rev-parse --show-toplevel)"

pytest "$@" applications_superstaq --cov
