#!/usr/bin/env bash

################################################################################
# Runs mypy on the repository
#
# Usage:
#     check/mypy [--flags]
################################################################################

# Get the working directory to the repo root.
cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$(git rev-parse --show-toplevel)"

echo -e -n "\033[31m"
mypy --config-file=.mypy.ini $@ applications_superstaq --exclude=examples/ --install-types --non-interactive
result=$?
echo -e -n "\033[0m"

exit ${result}
