name: Feature request
description: Suggest an idea for this project 🦅🐆
labels: ["kind/feature-request"]

body:
  - type: markdown
    attributes:
      value: Please make sure to browse the opened and closed issues to make sure that this idea has not previously been discussed.

  - type: textarea
    attributes:
      label: What is happening?
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: What are the current alternatives?
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Any additional context?
      description: Additional context for the issue, such as screenshots or suggestions for how a contributor should implement this.
    validations:
      required: false

  - type: markdown
    attributes:
      value: "### Please add the appropriate labels for this issue."
