[build-system]
build-backend = "setuptools.build_meta"
requires = [ "setuptools" ]

[project]
name = "checks-superstaq"
description = "Check script tools for Superstaq."
readme = { file = "README.md", content-type = "text/markdown" }
license = { text = "Apache-2.0" }
authors = [
  { name = "Superstaq development team", email = "superstaq@infleqtion.com" },
]
requires-python = ">=3.9.0"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
dynamic = [ "dependencies", "version" ]
urls.homepage = "https://github.com/Infleqtion/client-superstaq"

[tool.setuptools]
packages.find.include = [ "checks_superstaq*" ]
package-data.checks_superstaq = [ "checks-pyproject.toml", "py.typed" ]
dynamic.dependencies.file = [ "requirements.txt" ]
dynamic.version.attr = "checks_superstaq._version.__version__"

[tool.isort]
profile = "black"
color_output = true
line_length = 100
known_first_party = "checks_superstaq"

[tool.pyproject-fmt]
column_width = 100
max_supported_python = "3.14"
