# Check script configuration:

[tool.pytest.ini_options]
addopts = "--disable-socket"
filterwarnings = [
  "ignore::UserWarning:qtrl.*",
  "ignore::PendingDeprecationWarning:qtrl.utils.config",
  "ignore::PendingDeprecationWarning:ruamel.yaml.main",
]

[tool.ruff]
line-length = 100
target-version = "py39"
show-fixes = true

# Specific linting rules to enable in `ruff`
lint.select = [
  "A",      # flake8-builtins
  "ANN",    # flake8-annotations checks
  "ARG",    # Unused argument in a function/method
  "ASYNC",  # flake8-async
  "B",      # flake8-bugbear checks
  "C",      # flake8-comprehensions, mccabe checks
  "COM818", # trailing-comma-on-bare-tuple error
  "D",      # pydocstyle checks
  "DTZ",    # flake8-datetimez checks
  "E",      # pycodestyle checks
  "ERA",    # Commented-out code checks
  "F",      # pyflakes checks
  "FA",     # flake8-future-annotations checks
  "FAST",   # FastAPI checks
  "FBT003", # boolean-positional-value-in-call checks
  "FLY",    # flynt checks
  "FURB",   # refurb checks
  "G",      # flake8-logging-format
  "I",      # isort checks
  "ICN",    # flake8-import-conventions
  "ISC",    # flake8-implicit-str-concat checks
  "LOG",    # flake8-logging checks
  "N",      # pep8-naming
  "NPY",    # numpy-specific checks
  "PD",     # pandas-vet
  "PERF",   # Perflint checks
  "PGH",    # pygrep-hooks checks
  "PIE",    # flake8-pie checks
  "PL",     # pylint checks
  "PT",     # flake8-pytest-style
  "PYI",    # flake8-pyi checks
  "Q",      # flake8-quotes checks
  "RET",    # flake8-return checks
  "RSE",    # flake8-raise checks
  "RUF",    # Ruff-specific checks
  "S",      # flake8-bandit
  "SIM",    # flake8-simplify checks
  "SLOT",   # flake8-slots checks
  "T10",    # flake8-debugger checks
  "T20",    # flake8-print checks
  "TC",     # flake8-type-checking checks
  "TD",     # flake8-todos
  "TID",    # flake8-tidy-imports
  "TRY",    # tryceratops
  "UP",     # pyupgrade checks
  "W",      # pycodestyle warnings checks
]
lint.ignore = [
  "ANN401",  # Any type
  "ARG002",  # Unused method argument
  "ARG005",  # Unused lambda argument
  "B008",    # Function call in default argument
  "B019",    # Cached instance method
  "B023",    # Function uses loop variable
  "B904",    # Raise without from inside except
  "B905",    # zip without explicit strict
  "C409",    # unnecessary-literal-within-tuple-call (see https://github.com/astral-sh/ruff/issues/12912)
  "C416",    # Unnecessary comprehension (see https://docs.astral.sh/ruff/rules/unnecessary-comprehension/#known-problems)
  "D100",    # Undocumented public module
  "D104",    # Undocumented public package
  "D105",    # Undocumented magic method
  "D107",    # Undocumented public init
  "D205",    # Missing blank line after summary
  "FAST002", # FastAPI non-annotated dependency
  "N806",    # Non-lowercase variable in function
  "PERF401", # Manual list comprehension
  "PLR0911", # Too many return statements
  "PLR0912", # Too many branches
  "PLR0913", # Too many arguments
  "PLR0915", # Too many statements
  "PLR2004", # Magic value comparison
  "PLW2901", # Redefined loop name
  "PT012",   # Pytest raises with multiple statements
  "PT019",   # Pytest fixture param without value
  "PT022",   # Pytest useless yield fixture
  "PYI041",  # Redundant numeric union
  "RET504",  # Unnecessary assign
  "RUF001",  # Ambiguous Unicode character string
  "RUF002",  # Ambiguous Unicode character docstring
  "S101",    # Using asserts
  "S112",    # Try except continue
  "S310",    # Suspicious URL open usage
  "S603",    # Subprocess without shell equals true
  "S607",    # Start process with partial path
  "SIM102",  # Collapsible if
  "SIM105",  # Suppressible exception
  "SIM118",  # In dict keys
  "TC003",   # Typing-only standard-library import
  "TD002",   # Missing todo author
  "TD003",   # Missing todo link
  "TRY003",  # Raise vanilla args
  # The following are excluded to not conflict with `ruff format`:
  "COM812",  # Missing trailing comma
  "COM819",  # Prohibited trailing comma
  "D206",    # Docstring tab indentation
  "D300",    # Triple single quotes
  "E111",    # Indentation with invalid multiple
  "E114",    # Indentation with invalid multiple comment
  "E117",    # Over-indented
  "Q000",    # Bad quotes inline string
  "Q001",    # Bad quotes multiline string
  "Q002",    # Bad quotes docstring
  "Q003",    # Avoidable escaped quote
  "W191",    # Tab indentation
]

# Allow autofix for all enabled rules (when `--fix` is passed)
lint.fixable = ["ALL"]
lint.unfixable = []

# Allow unused variables when underscore-prefixed
lint.dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Enable `from __future__ import annotations` simplification for rules
lint.future-annotations = true

[tool.ruff.lint.flake8-type-checking]
exempt-modules = ["collections.abc"]

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint.per-file-ignores]
"*.ipynb" = ["D101", "D102", "D103", "E501", "ERA001", "T201"]
"*test.py" = ["D101", "D102", "D103", "N802", "N803", "S105", "S106"]

[tool.ruff.lint.pydocstyle]
convention = "google"
ignore-decorators = ["property", "classmethod", "staticmethod"]

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.ruff.lint.isort]
case-sensitive = false


[tool.mypy]
pretty = true
ignore_missing_imports = true
warn_redundant_casts = true
show_error_codes = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_untyped_defs = true
warn_unused_ignores = true
install_types = true
non_interactive = true
no_implicit_optional = true
plugins = ["pydantic.mypy"]

[tool.coverage.report]
fail_under = 100
show_missing = true
skip_covered = true
exclude_lines = ["pragma: no cover", "if TYPE_CHECKING:", "@overload"]

[tool.coverage.run]
include = ["./*"]
concurrency = ["thread"]
parallel = true
patch = ["subprocess"]

[tool.licensepy]
license_header_template = """Copyright {year} {licensee}

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
licensee = "Infleqtion"
