#!/usr/bin/env bash
set -euo pipefail

python -m pip install --upgrade pip setuptools wheel

python -m pip install "./general-superstaq[examples]"
python -m pip install "./cirq-superstaq[examples]"
python -m pip install "./qiskit-superstaq[examples]"
python -m pip install "./supermarq-benchmarks"
