name: Daily Integration Check

on:
  schedule:
    - cron: "0 14 * * *" # Daily at 14:00 UTC
  workflow_dispatch: # so that we can also run manually, e.g. for testing

jobs:
    daily-integration-check:
        name: Pytest integration check
        env:
            SUPERSTAQ_API_KEY: ${{ secrets.SUPERSTAQ_API_KEY }}
            TEST_USER_IBMQ_TOKEN: ${{ secrets.TEST_USER_IBMQ_TOKEN }}
            TEST_USER_IBMQ_INSTANCE: ${{ secrets.TEST_USER_IBMQ_INSTANCE }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                group: [1, 2, 3, 4, 5, 6]
        timeout-minutes: 15
        steps:
            - uses: actions/checkout@v6
            - name: Set up Python 3.14
              uses: actions/setup-python@v6
              with:
                  python-version: 3.14
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install ./checks-superstaq ./general-superstaq[dev] ./qiskit-superstaq[dev] ./cirq-superstaq[dev]
                  python -m pip install pytest-split
            - name: Pytest integration check (group ${{ matrix.group }}/6)
              run: |
                  touch .pytest-split-durations
                  checks/pytest_.py --integration --splits=6 --group=${{ matrix.group }} -v
            - name: Create issue if integration check failed
              if: ${{ failure() }}
              uses: JasonEtco/create-an-issue@v2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  TEST_USER_IBMQ_TOKEN: ${{ secrets.TEST_USER_IBMQ_TOKEN }}
                  TEST_USER_IBMQ_INSTANCE: ${{ secrets.TEST_USER_IBMQ_INSTANCE }}
              with:
                  filename: .github/integration-check-failure-issue.md
                  update_existing: true
