name: Hilbert Daily Integration Check

on:
  schedule:
  - cron: "0 14 * * *"  # Daily at 14:00 UTC
  workflow_dispatch:  # so that we can also run manually, e.g. for testing


jobs:
  hilbert-daily-integration-check:
    name: Pytest integration check
    env:
      SUPERSTAQ_API_KEY : ${{ secrets.SUPERSTAQ_API_KEY }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ./checks-superstaq ./general-superstaq[dev] ./qiskit-superstaq[dev] ./cirq-superstaq[dev]
      - name: Pytest integration check
        run: |
          pytest cirq-superstaq/cirq_superstaq/hilbert_daily_integration_test.py
          pytest qiskit-superstaq/qiskit_superstaq/hilbert_daily_integration_test.py
      - name: Create issue if integration check failed
        if: ${{ failure() }}
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/hilbert-integration-check-failure-issue.md
          update_existing: true
