name: Monthly Supermarq run

on:
  schedule:
    - cron: "0 12 1 * *" # Every first of the month at 12
  workflow_dispatch:  # So that we can also run manually, e.g. for testing

jobs:
  run-supermarq:
    runs-on: ubuntu-latest
    env:
      SUPERSTAQ_API_KEY : ${{ secrets.SUPERSTAQ_API_KEY }}
      IBMQ_TOKEN: ${{secrets.IBMQ_TOKEN}}
      HONEYWELL_PASSWORD: ${{secrets.HONEYWELL_PASSWORD}}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ./general-superstaq[dev] ./qiskit-superstaq[dev] ./cirq-superstaq[dev]
          pip install ./supermarq-benchmarks[dev]
      - name: Run Supermarq
        run: |
          python supermarq-benchmarks/supermarq/run_supermarq.py